### ISSUE TITLE
Error on profile mode

### ISSUE THREAD

**Issue by gagermaniac** [tomykho/midtrans_sdk#2]
Got this error when trying to run on profile mode,
debug mode working perfectly

Launching lib/main.dart on Nokia 5 1 Plus in profile mode...

Running Gradle task 'assembleProfile'...                        
/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:8: error: package com.google.gson does not exist

import com.google.gson.Gson;

                      ^

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:9: error: package com.google.gson.reflect does not exist

import com.google.gson.reflect.TypeToken;

                              ^

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:10: error: package com.midtrans.sdk.corekit.callback does not exist

import com.midtrans.sdk.corekit.callback.TransactionFinishedCallback;

                                        ^

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:11: error: package com.midtrans.sdk.corekit.core does not exist

import com.midtrans.sdk.corekit.core.Logger;

                                    ^

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:12: error: package com.midtrans.sdk.corekit.core does not exist

import com.midtrans.sdk.corekit.core.MidtransSDK;

                                    ^

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:13: error: package com.midtrans.sdk.corekit.core does not exist

import com.midtrans.sdk.corekit.core.UIKitCustomSetting;

                                    ^

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:14: error: package com.midtrans.sdk.corekit.core.themes does not exist

import com.midtrans.sdk.corekit.core.themes.CustomColorTheme;

                                           ^

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:15: error: package com.midtrans.sdk.corekit.models does not exist

import com.midtrans.sdk.corekit.models.TransactionResponse;

                                      ^

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:16: error: package com.midtrans.sdk.corekit.models.snap does not exist

import com.midtrans.sdk.corekit.models.snap.TransactionResult;

                                           ^

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:17: error: package com.midtrans.sdk.uikit does not exist

import com.midtrans.sdk.uikit.SdkUIFlowBuilder;

                             ^

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:96: error: cannot find symbol

    SdkUIFlowBuilder builder = SdkUIFlowBuilder.init()

    ^

  symbol:   class SdkUIFlowBuilder

  location: class MidtransSdkPlugin

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:102: error: cannot find symbol

            .setTransactionFinishedCallback(new TransactionFinishedCallback() {

                                                ^

  symbol:   class TransactionFinishedCallback

  location: class MidtransSdkPlugin

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:96: error: cannot find symbol

    SdkUIFlowBuilder builder = SdkUIFlowBuilder.init()

                               ^

  symbol:   variable SdkUIFlowBuilder

  location: class MidtransSdkPlugin

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:123: error: cannot find symbol

              new CustomColorTheme(

                  ^

  symbol:   class CustomColorTheme

  location: class MidtransSdkPlugin

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:141: error: cannot find symbol

    UIKitCustomSetting setting = new UIKitCustomSetting();

    ^

  symbol:   class UIKitCustomSetting

  location: class MidtransSdkPlugin

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:141: error: cannot find symbol

    UIKitCustomSetting setting = new UIKitCustomSetting();

                                     ^

  symbol:   class UIKitCustomSetting

  location: class MidtransSdkPlugin

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:160: error: cannot find symbol

    MidtransSDK.getInstance().setUIKitCustomSetting(setting);

    ^

  symbol:   variable MidtransSDK

  location: class MidtransSdkPlugin

/Users/gagermaniac/.pub-cache/hosted/pub.dartlang.org/midtrans_sdk-0.3.1/android/src/main/java/dev/tomykho/midtrans_sdk/MidtransSdkPlugin.java:166: error: cannot find symbol

    MidtransSDK.getInstance().startPaymentUiFlow(activity, token);

    ^

  symbol:   variable MidtransSDK

  location: class MidtransSdkPlugin

18 errors

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':midtrans_sdk:compileProfileJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
Running Gradle task 'assembleProfile'...                           41.8s
Exception: Gradle task assembleProfile failed with exit code 1

**Flutter Doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.3 19D76 darwin-x64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (4 available)

**Comment by tomykho** [comment]
Fixed in 0.3.2 https://github.com/tomykho/midtrans_sdk/commit/f521ef905fd3bf0be481f36df85756fd03015ab8
