### ISSUE TITLE
Couldn't find Gojek app installed on IOS

### ISSUE THREAD

**Issue by adlifaldiz** [tomykho/midtrans_sdk#7]
Screenshoot:
![393686FB-C707-40B4-B338-45D2F0A3371B](https://user-images.githubusercontent.com/32454728/161911605-fd989bb5-4718-4287-ab49-767449a4a902.jpeg)
![0ABC04E2-D78A-4D2A-B551-0E6DADC03E47](https://user-images.githubusercontent.com/32454728/161911590-ae14333a-fefa-42a5-80f7-a4dfba5e086c.jpeg)

i build my app with release mode and midtrans production. Midtrans couldn't find Gojek app installed on IOS.
I have followed the instruction to init midtrans.
Am i doing it the wrong way ?

Here is my flutter doctor -v:
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-ID)
    • Flutter version 2.10.2 at /Users/adlifaldiz/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (7 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/adlifaldiz/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.7759

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.0

[✓] Connected device (2 available)
    • MSG (mobile) • 00008030-001161693663802E • ios            • iOS 15.3.1
      19D52
    • Chrome (web) • chrome                    • web-javascript • Google Chrome
      97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by ravanstudio** [comment]
On iOS application web view, you need to add LSApplicationQueriesSchemes key to your app’s Info.plist, please find the detail on below code :
<key>LSApplicationQueriesSchemes</key>
<array>
<string>gojek</string>
</array>

**Comment by adlifaldiz** [comment]
Sorry for late reply,
Thank u, it works now.
